#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🐱‍🏍✨ Testing your project before committing'

# Check ESLint Standards
yarn lint-staged ||
(
        echo '😤🏀👋😤 Get that weak sh*t out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)





